### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by zuphilip** [kba/hocrjs#1]
I tried the demo page in Chrome under Windows it is not rendered correctly. The console says:
```
viewer.js:341Uncaught TypeError: fontSelect.append is not a functionObject.keys.forEach @ viewer.js:341addToolbar @ viewer.js:336init @ viewer.js:395(anonymous function) @ fullscreen-init.js:3(anonymous function) @ fullscreen-init.js:4
favicon.ico:1 GET https://kba.github.io/favicon.ico 404 (Not Found)
```
Moreover, also in Firefox and under Linux the demo page is not rendered correctly.

**Comment by kba** [comment]
Consider it pre-alpha at the moment. If you have any pointers as to the problem or a PR, I'll merge it. It works for me and releasing is not my main priority at the moment. I'll let you know when I find time to work on it, after the spec is getting to a point where it can be properly implemented.
