### ISSUE TITLE
Open sidebar disappears

### ISSUE THREAD

**Issue by zuphilip** [kba/hocrjs#11]
The possibility to open the sidebar after it is closed almost disappears in the new version - at least sometimes:

1. Open https://kba.github.io/hocrjs/example/426117689_0459.html
2. Close the sidebar at the left

![sidebar-disappeared](https://user-images.githubusercontent.com/5199995/34194954-7cd2cce6-e55b-11e7-86ee-8c1f17de7e4d.png)

This is with Firefox 58 (64-bit) under Windows.

**Comment by kba** [comment]
Works in Chrome https://youtu.be/fGpSn9jqmDI

Will test with firefox.

**Comment by kba** [comment]
Also works with Chrome in Windows.

**Comment by kba** [comment]
Indeed, it's a firefox issue. I'll get rid of the transformation.

**Comment by kba** [comment]
Fixed in [v0.3.4](https://github.com/kba/hocrjs/releases/tag/v0.3.4)

**Comment by zuphilip** [comment]
Wow, that was fast! Thank you!
