### ISSUE TITLE
Greasemonkey 4 has no menu command anymore

### ISSUE THREAD

**Issue by kba** [kba/hocrjs#12]

**Comment by zuphilip** [comment]
(We mostly switched to Tampermonkey for AutoLink script because of that.)

**Comment by kba** [comment]
Tampermonkey is the better engine, it's just unfortunate it's not Free Software.

**Comment by kba** [comment]
There's a polyfill for Greasmonkey 4 which adds the "Inject hOCR viewer" option in the context menu. Right click somewhere on the text to open it.
