### ISSUE TITLE
Paragraphs are positioned slighlty wrong

### ISSUE THREAD

**Issue by zuphilip** [kba/hocrjs#13]
The paragraphs are positioned slightly wrong. This is especially visible when you look at the different positions of the lines and paragraphs, e.g.

![hocrjs-par](https://user-images.githubusercontent.com/5199995/36062486-b81c264a-0e6d-11e8-8162-bccd2c866fc6.png)

In this image the heading "Auswahlbibliographie" is just one word in one line which is the whole paragraph. Therefore all boxes are the same, but the paragraph box (purple) is drawn too low. The same holds then for all other paragraph boxes.

**Comment by zuphilip** [comment]
Example: 
[309515696-2 tif](https://user-images.githubusercontent.com/5199995/36392519-f5c9ebd6-15ab-11e8-8e9d-9dec03d15b61.png)
[309515696-2.html.txt](https://github.com/kba/hocrjs/files/1737901/309515696-2.html.txt)

**Comment by kba** [comment]
Default for `<p>` is to use a vertical margin of ~1em for firefox/chrome. Should be normalized to not use any margin (since elements are positioned absolutely.)

**Comment by stweil** [comment]
Does PR‌ #19 improve the position?

**Comment by zuphilip** [comment]
I think what @kba means is that we need in CSS somewhere
```css
p {
   margin: 0;
}
```
which indeed seems to solve the issue here.

But I don't know in which file we need to write this.

**Comment by kba** [comment]
Added to HocrViewer component in vue-hocr, fixed in 0.4.0-1, updating from https://unpkg.com/hocrjs should update to this version.
