### ISSUE TITLE
Font Scale Errors

### ISSUE THREAD

**Issue by zuphilip** [kba/hocrjs#15]
The scaling of the fonts look sometimes wrong, e.g. last word in

![font-scaling-error](https://user-images.githubusercontent.com/5199995/37855881-e154d7a6-2ef1-11e8-9e8a-4a90b55c44b6.png)

The problem seems to be that "Staatsanzeiger" already occured before in the normal text and there the font-scale `37px` was calculated. The same font-scale is taken here for the heading which is wrong. AFAIU this is a consequences of this caching in [ScaleFont.js](https://github.com/kba/hocrjs/blob/master/vue-hocr/src/components/HocrViewer/feature/ScaleFont.js), which will reuse values found earlier:
```js
    if (!(text in this.cache)) {
       ....
    }
    el.style.fontSize = this.cache[text] + 'px'
```

Should we deactivate this wrong cashing? Or how can this be fixed otherwise? CC @stweil

**Comment by zuphilip** [comment]
Another example:

![hocrjs-font-sizes](https://user-images.githubusercontent.com/5199995/37863800-9913ccf4-2f64-11e8-85bd-bd3a5d050871.png)

The "Vorarlberger" and "Bregenz" on the right are too large, because the same font size is taken as on the left.

**Comment by stweil** [comment]
I think we have to disable it if `ScaleFont` is enabled.

**Comment by stweil** [comment]
Disabling the cache works (see https://digi.bib.uni-mannheim.de/hocrjs@0.3.5/dist/0404.html), but the time for scaling the fonts increases from about 8 s to 12 s.

**Comment by zuphilip** [comment]
Is it needed to change from non-scaled to scaled fonts and back again in the Reichsanzeiger use case? Otherwise we could calculate the font size in advance and save the `style`-attribute back to the hocr files. Maybe also some global server-side caching which besides the text also considers the height and width of the boxes could work.

**Comment by kba** [comment]
That feature should help getting a feel for the font type/size and have a better overview of text distribution when zoomed out in large documents. Mostly, it was an experiment in how to calculate the right font height as fast as possible while showing text as large as possible.

Without caching, newspaper pages or in general pages with lots of repeated words will block the browser (tab) for a long time, as you noticed.

A quickfix would be to use word + box width rounded to the closest 10 as the cache key but this would result in many more cache misses.

Another approach would be to allow zooming the text only, which can be done with css and a slider and is much faster than iterating through all elements.

**Comment by zuphilip** [comment]
@stweil told me that he experimented with a speed up of the current implementation w/o caching and was seeing 10x faster results.
