### ISSUE TITLE
Toggle only some levels active

### ISSUE THREAD

**Issue by zuphilip** [kba/hocrjs#3]
It would be nice to have options for `ocr_carea`, `ocr_par`, `ocr_line`, `ocrx_word` to deactivate/active this level in the output. Currently, I do this manually by changing on the browser console:

![hocr-js-borders](https://cloud.githubusercontent.com/assets/5199995/23293334/ddd6dc8a-fa65-11e6-95ae-c4f51e844aad.jpg)

**Comment by kba** [comment]
You mean something like this:  https://youtu.be/9aqBDbiSzbg?

Try https://github.com/kba/hocrjs/pull/7

**Comment by zuphilip** [comment]
Yes, what the video shows. However, it looks that these are different from the hocr-levels I mentioned above? Will you continue the PR?

**Comment by kba** [comment]
Currently, just three levels are distinguished (area = carea & par, line, inline = words). I'll make that more specific in #7.

**Comment by kba** [comment]
highlighting of carea, par, line and elements within a line can now be toggled.

**Comment by zuphilip** [comment]
Wow, very nice! Thank you! 🙇 

I am not sure that the option `hightligh` is now still needed. Moreover, what is `highlightNotPage` and is it maybe unneeded?

**Comment by kba** [comment]
`highlight` toggles all highlighting at once. `highlightNotPage` highlights everything that is within a page so you quickly see areas where the OCR didn't recognize anything at all, to spot images and such.

"Needed" depends on your use case. I do find them useful but you can always disable these features (they are by default).

**Comment by zuphilip** [comment]
Okay, good to know that these are useful for you. Thank you again!
