### ISSUE TITLE
 Readme.md

### ISSUE THREAD

**Issue by madhancr** [kba/hocrjs#5]
Add info on how to run the project in Readme.md ?

**Comment by kba** [comment]
Have a look at the [demo](view-source:https://kba.github.io/hocrjs/example/426117689_0459.html):

```html
  <script src="../dist/hocr-fullscreen.webpack.js"></script>
```

Adds the packed JS to the hocr file.

Or install the user script, open a hocr-flavored HTML file and select "Inject hocr" from the user script menu.

If you want to contribute documentation / fixes, I'll gladly accept PR :-)

**Comment by kba** [comment]
There's also a binary `hocr-inject` which adds script and css tags to local hocr files, see https://github.com/kba/hocrjs/blob/master/src/bin/hocrjs-inject.js

**Comment by madhancr** [comment]
I am not a web developer so looking for instructions on how to run demo project. 
I see package.json so this is probably using node.js project (just know enough to guess this :) 
It will help if you can add steps in the readme so anyone follow it and run the demo (like git clone, npm install etc)

**Comment by zuphilip** [comment]
I try to add some words in the README file as a start...

In the mean time: Here is jsfiddle for demonstrating where you can replace the html (top-left part) with your `hocr` content and then press `run` https://jsfiddle.net/2a62vtb9/2/ .

**Comment by kba** [comment]
I've refactored the code and updated the README. Now you only need to add

```html
<script src="https://unpkg.com/hocrjs"/>
```

to the hOCR document before the closing `</body>` tag, no more style tag.

Or you can use the [user script](https://unpkg.com/hocrjs/dist/hocr.user.js) to do that with a single click.

Or run the `hocrjs-inject` binary to add the `<script>` tag to local files.

This was a breaking change, the script names and URLs changed. Will be versioned from now on, current version is [0.1.1](https://www.npmjs.com/package/hocrjs).

**Comment by madhancr** [comment]
thx! that was helpful.
