### ISSUE TITLE
Problem parsing hocr-files with hocrjs versions > 0.2.0 

### ISSUE THREAD

**Issue by Hyper-Node** [kba/hocrjs#9]
Hello @kba,

at the moment the below hocr-file generated by tesseract 4.0.0  is not shown correctly in browsers by versions 0.2.1 and 0.3.2 (it's .txt because of git restrictions) when using the inject-ocr grease-/tampermonkey plugin as well as the nodejs hocr-injector. Same issue also for a file generated with abbyy. 

Showing hocr-js works by pointing to the old version of hocrjs, like this (in browser plugin): 
`      script.src = "https://unpkg.com/hocrjs@0.2.0/dist/hocr.fullscreen.js?cachebuster=" + ....
`

[oneprof_tesseract_cli.html.txt](https://github.com/kba/hocrjs/files/1572103/oneprof_tesseract_cli.html.txt)

**Comment by kba** [comment]
Tesseract adds a property `x_size` that hocr-dom chokes on. That can be disabled (https://github.com/kba/hocr-dom/blob/master/hocr-dom/src/property-parser.js#L15) but it's enabled by default.

I'll make this configurable.

**Comment by kba** [comment]
Engine-specific properties are now allowed by default, try [v0.3.3](https://github.com/kba/hocrjs/releases/tag/v0.3.3). If you provide ABBYY output as well, I'll be happy to test.

**Comment by kba** [comment]
BTW would it be okay to add that sample to https://github.com/kba/ocr-fileformat-samples/blob/master/samples/hocr/1.1 ?

**Comment by stweil** [comment]
This issue is still there because of an inconsistency between hocr-dom sources and hocr-dom registered package. See https://github.com/kba/hocr-dom/issues/2.

**Comment by kba** [comment]
Should be fixed in hocrjs 0.4.0-2 / hocr-dom 0.1.4.
